#! /bin/python3
import json
from os import getcwd, listdir,system
from os.path import isfile,join,basename

from sys import argv

class colors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    END = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


def isvalid(filename:str) -> bool:
    with open(filename,"r") as f:
        try:
            json.load(f)
            return True
        except:
            return False
    




def main():
    endstring = f""
    cwd = getcwd()
    test_files =[join(cwd,x) for x in listdir(cwd) if ( isfile(x) )]
    test_files.sort()
    print(test_files)
    passed = True
    for file in test_files:
        print(f"\n{colors.HEADER}testing {file} {colors.END}")
        if not isvalid(file):
            print(f"{colors.WARNING}\tis not valid json,skipping{colors.END}")
            continue;
        retval = system("../build/main " + file)
        print(f"{colors.BOLD}\texited with signal {retval} {colors.END}")

        if( retval != 0):
            endstring += f"{colors.FAIL} {basename(file)} failed   ✗{colors.END}\n"
        else:
            endstring += f"{colors.OKGREEN} {basename(file)} success! ✓{colors.END}\n"

        passed = passed and ( retval == 0)

    print(f"{colors.BOLD}TESTS:{colors.END}")
    if passed:
        print(f"{colors.OKGREEN}all tests passed {colors.END}")
    else:
        print(f"{colors.FAIL}not passed {colors.END}")
            

    print(endstring)

        



if __name__ =="__main__":
    main()

